/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppInlaysRouteImport } from './routes/_app/inlays'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppCatalogIndexRouteImport } from './routes/_app/catalog.index'
import { Route as AppProjectsCreateProjectRouteImport } from './routes/_app/projects_.create-project'
import { Route as AppDealershipIdRouteImport } from './routes/_app/dealership.$id'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin.users'
import { Route as AppAdminPriceGroupsRouteImport } from './routes/_app/admin.price-groups'
import { Route as AppAdminDealershipsRouteImport } from './routes/_app/admin.dealerships'
import { Route as AppAdminCatalogRouteImport } from './routes/_app/admin.catalog'
import { Route as AppProjectsCreateProjectIndexRouteImport } from './routes/_app/projects_.create-project.index'
import { Route as AppProjectsIdIndexRouteImport } from './routes/_app/projects_.$id.index'
import { Route as AppProjectsCreateProjectAddInlayRouteImport } from './routes/_app/projects_.create-project.add-inlay'
import { Route as AppProjectsIdAddInlayRouteImport } from './routes/_app/projects_.$id.add-inlay'
import { Route as AppDealershipIdUsersRouteImport } from './routes/_app/dealership.$id.users'
import { Route as AppDealershipIdSettingsRouteImport } from './routes/_app/dealership.$id.settings'
import { Route as AppAdminUsersInternalRouteImport } from './routes/_app/admin.users.internal'
import { Route as AppAdminUsersDealershipRouteImport } from './routes/_app/admin.users.dealership'
import { Route as AppAdminCatalogCreateRouteImport } from './routes/_app/admin.catalog_.create'
import { Route as AppAdminCatalogUuidRouteImport } from './routes/_app/admin.catalog_.$uuid'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppInlaysRoute = AppInlaysRouteImport.update({
  id: '/inlays',
  path: '/inlays',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogIndexRoute = AppCatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsCreateProjectRoute =
  AppProjectsCreateProjectRouteImport.update({
    id: '/projects_/create-project',
    path: '/projects/create-project',
    getParentRoute: () => AppRoute,
  } as any)
const AppDealershipIdRoute = AppDealershipIdRouteImport.update({
  id: '/dealership/$id',
  path: '/dealership/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPriceGroupsRoute = AppAdminPriceGroupsRouteImport.update({
  id: '/price-groups',
  path: '/price-groups',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDealershipsRoute = AppAdminDealershipsRouteImport.update({
  id: '/dealerships',
  path: '/dealerships',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCatalogRoute = AppAdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppProjectsCreateProjectIndexRoute =
  AppProjectsCreateProjectIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsCreateProjectRoute,
  } as any)
const AppProjectsIdIndexRoute = AppProjectsIdIndexRouteImport.update({
  id: '/projects_/$id/',
  path: '/projects/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsCreateProjectAddInlayRoute =
  AppProjectsCreateProjectAddInlayRouteImport.update({
    id: '/add-inlay',
    path: '/add-inlay',
    getParentRoute: () => AppProjectsCreateProjectRoute,
  } as any)
const AppProjectsIdAddInlayRoute = AppProjectsIdAddInlayRouteImport.update({
  id: '/projects_/$id/add-inlay',
  path: '/projects/$id/add-inlay',
  getParentRoute: () => AppRoute,
} as any)
const AppDealershipIdUsersRoute = AppDealershipIdUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppDealershipIdRoute,
} as any)
const AppDealershipIdSettingsRoute = AppDealershipIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppDealershipIdRoute,
} as any)
const AppAdminUsersInternalRoute = AppAdminUsersInternalRouteImport.update({
  id: '/internal',
  path: '/internal',
  getParentRoute: () => AppAdminUsersRoute,
} as any)
const AppAdminUsersDealershipRoute = AppAdminUsersDealershipRouteImport.update({
  id: '/dealership',
  path: '/dealership',
  getParentRoute: () => AppAdminUsersRoute,
} as any)
const AppAdminCatalogCreateRoute = AppAdminCatalogCreateRouteImport.update({
  id: '/catalog_/create',
  path: '/catalog/create',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCatalogUuidRoute = AppAdminCatalogUuidRouteImport.update({
  id: '/catalog_/$uuid',
  path: '/catalog/$uuid',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/inlays': typeof AppInlaysRoute
  '/projects': typeof AppProjectsRoute
  '/settings': typeof AppSettingsRoute
  '/admin/catalog': typeof AppAdminCatalogRoute
  '/admin/dealerships': typeof AppAdminDealershipsRoute
  '/admin/price-groups': typeof AppAdminPriceGroupsRoute
  '/admin/users': typeof AppAdminUsersRouteWithChildren
  '/dealership/$id': typeof AppDealershipIdRouteWithChildren
  '/projects/create-project': typeof AppProjectsCreateProjectRouteWithChildren
  '/catalog/': typeof AppCatalogIndexRoute
  '/admin/catalog/$uuid': typeof AppAdminCatalogUuidRoute
  '/admin/catalog/create': typeof AppAdminCatalogCreateRoute
  '/admin/users/dealership': typeof AppAdminUsersDealershipRoute
  '/admin/users/internal': typeof AppAdminUsersInternalRoute
  '/dealership/$id/settings': typeof AppDealershipIdSettingsRoute
  '/dealership/$id/users': typeof AppDealershipIdUsersRoute
  '/projects/$id/add-inlay': typeof AppProjectsIdAddInlayRoute
  '/projects/create-project/add-inlay': typeof AppProjectsCreateProjectAddInlayRoute
  '/projects/$id/': typeof AppProjectsIdIndexRoute
  '/projects/create-project/': typeof AppProjectsCreateProjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/inlays': typeof AppInlaysRoute
  '/projects': typeof AppProjectsRoute
  '/settings': typeof AppSettingsRoute
  '/admin/catalog': typeof AppAdminCatalogRoute
  '/admin/dealerships': typeof AppAdminDealershipsRoute
  '/admin/price-groups': typeof AppAdminPriceGroupsRoute
  '/admin/users': typeof AppAdminUsersRouteWithChildren
  '/dealership/$id': typeof AppDealershipIdRouteWithChildren
  '/catalog': typeof AppCatalogIndexRoute
  '/admin/catalog/$uuid': typeof AppAdminCatalogUuidRoute
  '/admin/catalog/create': typeof AppAdminCatalogCreateRoute
  '/admin/users/dealership': typeof AppAdminUsersDealershipRoute
  '/admin/users/internal': typeof AppAdminUsersInternalRoute
  '/dealership/$id/settings': typeof AppDealershipIdSettingsRoute
  '/dealership/$id/users': typeof AppDealershipIdUsersRoute
  '/projects/$id/add-inlay': typeof AppProjectsIdAddInlayRoute
  '/projects/create-project/add-inlay': typeof AppProjectsCreateProjectAddInlayRoute
  '/projects/$id': typeof AppProjectsIdIndexRoute
  '/projects/create-project': typeof AppProjectsCreateProjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inlays': typeof AppInlaysRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/admin/catalog': typeof AppAdminCatalogRoute
  '/_app/admin/dealerships': typeof AppAdminDealershipsRoute
  '/_app/admin/price-groups': typeof AppAdminPriceGroupsRoute
  '/_app/admin/users': typeof AppAdminUsersRouteWithChildren
  '/_app/dealership/$id': typeof AppDealershipIdRouteWithChildren
  '/_app/projects_/create-project': typeof AppProjectsCreateProjectRouteWithChildren
  '/_app/catalog/': typeof AppCatalogIndexRoute
  '/_app/admin/catalog_/$uuid': typeof AppAdminCatalogUuidRoute
  '/_app/admin/catalog_/create': typeof AppAdminCatalogCreateRoute
  '/_app/admin/users/dealership': typeof AppAdminUsersDealershipRoute
  '/_app/admin/users/internal': typeof AppAdminUsersInternalRoute
  '/_app/dealership/$id/settings': typeof AppDealershipIdSettingsRoute
  '/_app/dealership/$id/users': typeof AppDealershipIdUsersRoute
  '/_app/projects_/$id/add-inlay': typeof AppProjectsIdAddInlayRoute
  '/_app/projects_/create-project/add-inlay': typeof AppProjectsCreateProjectAddInlayRoute
  '/_app/projects_/$id/': typeof AppProjectsIdIndexRoute
  '/_app/projects_/create-project/': typeof AppProjectsCreateProjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/inlays'
    | '/projects'
    | '/settings'
    | '/admin/catalog'
    | '/admin/dealerships'
    | '/admin/price-groups'
    | '/admin/users'
    | '/dealership/$id'
    | '/projects/create-project'
    | '/catalog/'
    | '/admin/catalog/$uuid'
    | '/admin/catalog/create'
    | '/admin/users/dealership'
    | '/admin/users/internal'
    | '/dealership/$id/settings'
    | '/dealership/$id/users'
    | '/projects/$id/add-inlay'
    | '/projects/create-project/add-inlay'
    | '/projects/$id/'
    | '/projects/create-project/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/inlays'
    | '/projects'
    | '/settings'
    | '/admin/catalog'
    | '/admin/dealerships'
    | '/admin/price-groups'
    | '/admin/users'
    | '/dealership/$id'
    | '/catalog'
    | '/admin/catalog/$uuid'
    | '/admin/catalog/create'
    | '/admin/users/dealership'
    | '/admin/users/internal'
    | '/dealership/$id/settings'
    | '/dealership/$id/users'
    | '/projects/$id/add-inlay'
    | '/projects/create-project/add-inlay'
    | '/projects/$id'
    | '/projects/create-project'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/inlays'
    | '/_app/projects'
    | '/_app/settings'
    | '/_app/admin/catalog'
    | '/_app/admin/dealerships'
    | '/_app/admin/price-groups'
    | '/_app/admin/users'
    | '/_app/dealership/$id'
    | '/_app/projects_/create-project'
    | '/_app/catalog/'
    | '/_app/admin/catalog_/$uuid'
    | '/_app/admin/catalog_/create'
    | '/_app/admin/users/dealership'
    | '/_app/admin/users/internal'
    | '/_app/dealership/$id/settings'
    | '/_app/dealership/$id/users'
    | '/_app/projects_/$id/add-inlay'
    | '/_app/projects_/create-project/add-inlay'
    | '/_app/projects_/$id/'
    | '/_app/projects_/create-project/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inlays': {
      id: '/_app/inlays'
      path: '/inlays'
      fullPath: '/inlays'
      preLoaderRoute: typeof AppInlaysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/': {
      id: '/_app/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof AppCatalogIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects_/create-project': {
      id: '/_app/projects_/create-project'
      path: '/projects/create-project'
      fullPath: '/projects/create-project'
      preLoaderRoute: typeof AppProjectsCreateProjectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dealership/$id': {
      id: '/_app/dealership/$id'
      path: '/dealership/$id'
      fullPath: '/dealership/$id'
      preLoaderRoute: typeof AppDealershipIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/price-groups': {
      id: '/_app/admin/price-groups'
      path: '/price-groups'
      fullPath: '/admin/price-groups'
      preLoaderRoute: typeof AppAdminPriceGroupsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/dealerships': {
      id: '/_app/admin/dealerships'
      path: '/dealerships'
      fullPath: '/admin/dealerships'
      preLoaderRoute: typeof AppAdminDealershipsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/catalog': {
      id: '/_app/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AppAdminCatalogRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/projects_/create-project/': {
      id: '/_app/projects_/create-project/'
      path: '/'
      fullPath: '/projects/create-project/'
      preLoaderRoute: typeof AppProjectsCreateProjectIndexRouteImport
      parentRoute: typeof AppProjectsCreateProjectRoute
    }
    '/_app/projects_/$id/': {
      id: '/_app/projects_/$id/'
      path: '/projects/$id'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof AppProjectsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects_/create-project/add-inlay': {
      id: '/_app/projects_/create-project/add-inlay'
      path: '/add-inlay'
      fullPath: '/projects/create-project/add-inlay'
      preLoaderRoute: typeof AppProjectsCreateProjectAddInlayRouteImport
      parentRoute: typeof AppProjectsCreateProjectRoute
    }
    '/_app/projects_/$id/add-inlay': {
      id: '/_app/projects_/$id/add-inlay'
      path: '/projects/$id/add-inlay'
      fullPath: '/projects/$id/add-inlay'
      preLoaderRoute: typeof AppProjectsIdAddInlayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dealership/$id/users': {
      id: '/_app/dealership/$id/users'
      path: '/users'
      fullPath: '/dealership/$id/users'
      preLoaderRoute: typeof AppDealershipIdUsersRouteImport
      parentRoute: typeof AppDealershipIdRoute
    }
    '/_app/dealership/$id/settings': {
      id: '/_app/dealership/$id/settings'
      path: '/settings'
      fullPath: '/dealership/$id/settings'
      preLoaderRoute: typeof AppDealershipIdSettingsRouteImport
      parentRoute: typeof AppDealershipIdRoute
    }
    '/_app/admin/users/internal': {
      id: '/_app/admin/users/internal'
      path: '/internal'
      fullPath: '/admin/users/internal'
      preLoaderRoute: typeof AppAdminUsersInternalRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
    '/_app/admin/users/dealership': {
      id: '/_app/admin/users/dealership'
      path: '/dealership'
      fullPath: '/admin/users/dealership'
      preLoaderRoute: typeof AppAdminUsersDealershipRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
    '/_app/admin/catalog_/create': {
      id: '/_app/admin/catalog_/create'
      path: '/catalog/create'
      fullPath: '/admin/catalog/create'
      preLoaderRoute: typeof AppAdminCatalogCreateRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/catalog_/$uuid': {
      id: '/_app/admin/catalog_/$uuid'
      path: '/catalog/$uuid'
      fullPath: '/admin/catalog/$uuid'
      preLoaderRoute: typeof AppAdminCatalogUuidRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminUsersRouteChildren {
  AppAdminUsersDealershipRoute: typeof AppAdminUsersDealershipRoute
  AppAdminUsersInternalRoute: typeof AppAdminUsersInternalRoute
}

const AppAdminUsersRouteChildren: AppAdminUsersRouteChildren = {
  AppAdminUsersDealershipRoute: AppAdminUsersDealershipRoute,
  AppAdminUsersInternalRoute: AppAdminUsersInternalRoute,
}

const AppAdminUsersRouteWithChildren = AppAdminUsersRoute._addFileChildren(
  AppAdminUsersRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminCatalogRoute: typeof AppAdminCatalogRoute
  AppAdminDealershipsRoute: typeof AppAdminDealershipsRoute
  AppAdminPriceGroupsRoute: typeof AppAdminPriceGroupsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRouteWithChildren
  AppAdminCatalogUuidRoute: typeof AppAdminCatalogUuidRoute
  AppAdminCatalogCreateRoute: typeof AppAdminCatalogCreateRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminCatalogRoute: AppAdminCatalogRoute,
  AppAdminDealershipsRoute: AppAdminDealershipsRoute,
  AppAdminPriceGroupsRoute: AppAdminPriceGroupsRoute,
  AppAdminUsersRoute: AppAdminUsersRouteWithChildren,
  AppAdminCatalogUuidRoute: AppAdminCatalogUuidRoute,
  AppAdminCatalogCreateRoute: AppAdminCatalogCreateRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppDealershipIdRouteChildren {
  AppDealershipIdSettingsRoute: typeof AppDealershipIdSettingsRoute
  AppDealershipIdUsersRoute: typeof AppDealershipIdUsersRoute
}

const AppDealershipIdRouteChildren: AppDealershipIdRouteChildren = {
  AppDealershipIdSettingsRoute: AppDealershipIdSettingsRoute,
  AppDealershipIdUsersRoute: AppDealershipIdUsersRoute,
}

const AppDealershipIdRouteWithChildren = AppDealershipIdRoute._addFileChildren(
  AppDealershipIdRouteChildren,
)

interface AppProjectsCreateProjectRouteChildren {
  AppProjectsCreateProjectAddInlayRoute: typeof AppProjectsCreateProjectAddInlayRoute
  AppProjectsCreateProjectIndexRoute: typeof AppProjectsCreateProjectIndexRoute
}

const AppProjectsCreateProjectRouteChildren: AppProjectsCreateProjectRouteChildren =
  {
    AppProjectsCreateProjectAddInlayRoute:
      AppProjectsCreateProjectAddInlayRoute,
    AppProjectsCreateProjectIndexRoute: AppProjectsCreateProjectIndexRoute,
  }

const AppProjectsCreateProjectRouteWithChildren =
  AppProjectsCreateProjectRoute._addFileChildren(
    AppProjectsCreateProjectRouteChildren,
  )

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppInlaysRoute: typeof AppInlaysRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppDealershipIdRoute: typeof AppDealershipIdRouteWithChildren
  AppProjectsCreateProjectRoute: typeof AppProjectsCreateProjectRouteWithChildren
  AppCatalogIndexRoute: typeof AppCatalogIndexRoute
  AppProjectsIdAddInlayRoute: typeof AppProjectsIdAddInlayRoute
  AppProjectsIdIndexRoute: typeof AppProjectsIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppInlaysRoute: AppInlaysRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppDealershipIdRoute: AppDealershipIdRouteWithChildren,
  AppProjectsCreateProjectRoute: AppProjectsCreateProjectRouteWithChildren,
  AppCatalogIndexRoute: AppCatalogIndexRoute,
  AppProjectsIdAddInlayRoute: AppProjectsIdAddInlayRoute,
  AppProjectsIdIndexRoute: AppProjectsIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
