packages:
  - apps/*
  - libs/*

catalog:
  '@tanstack/solid-form': ^1.28.0
  '@tanstack/solid-router': ^1.157.18
  prettier: ^3.8.1
  tailwindcss: ^3.4.19
  typescript: ^5.9.3

catalogs:
  solid:
    solid-js: ^1.9.11

onlyBuiltDependencies:
  - esbuild
  - sharp
