packages:
  - apps/*
  - libs/*

catalog:
  '@tanstack/solid-form': ^1.12.3
  typescript: ^5.8.3
  tailwindcss: ^3.4.17
  prettier: ^3.5.3

catalogs:
  solid:
    solid-js: ^1.9.7

onlyBuiltDependencies:
  - esbuild
  - sharp
