packages:
  - apps/*
  - libs/*

catalog:
  '@tanstack/solid-form': ^1.15.1
  prettier: ^3.6.2
  tailwindcss: ^3.4.17
  typescript: ^5.9.2

catalogs:
  solid:
    solid-js: ^1.9.7

onlyBuiltDependencies:
  - esbuild
  - sharp
