packages:
  - apps/*
  - libs/*

catalog:
  '@tanstack/solid-form': ^1.28.3
  '@tanstack/solid-router': ^1.163.3
  prettier: ^3.8.1
  tailwindcss: ^3.4.19
  typescript: ^5.9.3

catalogs:
  eslint:
    '@eslint/js': ^10.0.1
    eslint: ^10.0.2
    eslint-plugin-solid: ^0.14.5
    globals: ^17.3.0
    typescript-eslint: ^8.56.1
  solid:
    solid-js: ^1.9.11

onlyBuiltDependencies:
  - esbuild
  - sharp
