Table users {
	id integer [ pk, increment, not null, unique ]
	uuid uuid [ not null, unique ]
	name text [ not null ]
	email text [ not null, unique ]
	avatar text [ not null ]
	dealership_id integer [ not null ]
	created_at timestamptz [ not null ]
	updated_at timestamptz [ not null ]
	version integer [ not null ]
}

Table accounts {
	id integer [ pk, increment, not null, unique ]
	uuid uuid [ not null, unique ]
	user_id integer [ not null ]
	type varchar [ not null ]
	provider varchar [ not null ]
	provider_account_id varchar [ not null ]
	created_at timestamptz [ not null ]
	updated_at timestamptz [ not null ]
	version integer [ not null ]
}

Table tokens {
	hash bytea [ pk, not null, unique ]
	user_id integer [ not null ]
	expiry timestamptz [ not null ]
	scope text [ not null ]
}

Table dealerships {
	id integer [ pk, increment, not null, unique ]
	uuid uuid [ not null, unique ]
	name text [ not null, unique ]
	address text [ not null ]
	location point [ not null ]
	created_at timestamptz [ not null ]
	updated_at timestamptz [ not null ]
	version integer [ not null ]
}

Table inlay_proofs {
	id integer [ pk, increment, not null, unique ]
	uuid uuid [ not null, unique ]
	status varchar [ not null ]
	project_id integer [ not null ]
	inlay_id integer [ not null ]
	created_at timestamptz [ not null ]
	updated_at timestamptz [ not null ]
	version integer [ not null ]
}

Table projects {
	id integer [ pk, increment, not null, unique ]
	uuid uuid [ not null, unique ]
	status varchar [ not null ]
	approved boolean [ not null ]
	order_id integer [ not null ]
	dealership_id integer [ not null ]
	shipment_id integer [ not null ]
	created_at timestamptz [ not null ]
	updated_at timestamptz [ not null ]
	version integer [ not null ]
}

Table inlay_milestones {
	id integer [ pk, increment, not null, unique ]
	uuid uuid [ not null, unique ]
	type varchar [ not null ]
	event_type varchar [ not null ]
	event_time timestamptz [ not null ]
	project_id integer [ not null ]
	created_at timestamptz [ not null ]
	updated_at timestamptz [ not null ]
	version integer [ not null ]
}

Table audit_logs {
	id integer [ pk, increment, not null, unique ]
	table_name text [ not null ]
	record_id integer [ not null ]
	action varchar [ not null ]
	changed_by integer
	changed_at timestamptz [ not null ]
	old_data jsonb
	new_data jsonb
}

Table shipments {
	id integer [ pk, increment, not null, unique ]
	uuid uuid [ not null, unique ]
	created_at timestamptz [ not null ]
	updated_at timestamptz [ not null ]
	version integer [ not null ]
}

Table inlays {
	id integer [ pk, increment, not null, unique ]
	uuid uuid [ not null, unique ]
	created_at timestamptz [ not null ]
	updated_at timestamptz [ not null ]
	version integer [ not null ]
}

